### ISSUE TITLE
Workspaces API

### ISSUE THREAD

**Issue by goofmint** [b-eee/hexabase-sdk#52]
- [x] [GetWorkspaces](https://apidoc.hexabase.com/docs/v0/workspaces/GetWorkspaces)
- [x] [SelectWorkspace](https://apidoc.hexabase.com/docs/v0/workspaces/SelectWorkspace)
- [ ] [CreateNewWorkspace](https://apidoc.hexabase.com/docs/v0/workspaces/CreateNewWorkspace)
- [ ] [GetPasswordPolicy](https://apidoc.hexabase.com/docs/v0/workspaces/GetPasswordPolicy)
- [ ] [GetWorkspaceUsage](https://apidoc.hexabase.com/docs/v0/workspaces/GetWorkspaceUsage)
- [ ] [GetWorkspaceFunctionality](https://apidoc.hexabase.com/docs/v0/workspaces/GetWorkspaceFunctionality)

**Comment by goofmint** [comment]
@Hokutosei Hi. When should we use **SelectWorkspace API** ? We pass the workspace id when we call GetApplicationsAndDatastores like `/api/v0/workspaces/:workspace-id/applications`. 

So I think we don't need to implement this API in our SDK.

**Comment by Hokutosei** [comment]
@goofmint thank you very much for reviewing the api and sdk. for SelectWorkspace api usage, this has may have many use case , but I could only think one as of now:

1) some API may fetch/set data from different workspace, but may not call `GetApplicationsAndDatastore`
